### ISSUE TITLE
Add support for Winston 3.0

### ISSUE THREAD

**Issue by bra1n** [timdp/winston-aws-cloudwatch#88] opened 2018-08-14 11:46 UTC
It seems like this module is not fully compatible with Winston 3.0 yet, whenever I use `winston.add(new CloudWatchTransport(config));` I get the following log message:
```
undefined is a legacy winston transport. Consider upgrading: 
- Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```
Would be great if Winston 3.0 could be fully supported, too.

**Comment by timdp** [comment] 2018-08-14 16:06
Agreed. This is actually a duplicate of #80. The `winston3` branch should actually work already, but it's unfinished.

**Closed as completed by timdp** 2018-08-14 16:06 UTC
